# Adapted from https://github.com/glue-viz/conda-dev/blob/master/appveyor.yml

environment:
  global:
    PYTHON: "C:\\conda"
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci-helpers\\appveyor\\windows_sdk.cmd"
    PYTHON_ARCH: "64"
    PYTHON_VERSION: "3.7"
    CONDA_DEPENDENCIES: "conda-build anaconda-client"

platform:
  - x86
  - x64

install:
  - git clone --depth 1 https://github.com/astropy/ci-helpers.git
  - powershell ci-helpers/appveyor/install-miniconda.ps1
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - activate test

build: false

test_script:
  - python build-all.py
